# frozen_string_literal: true

require "zlib"

module Foundation
  # Deterministic application icon (SPEC M10.2).
  #
  # The mark is a placeholder derived from exactly one input — the
  # `brand_seed_color` in config/foundation.yml — so it can always be
  # regenerated from committed configuration instead of shipping an opaque
  # binary. `bin/rails foundation:icon` writes the SVG and PNG sizes under
  # public/, and tests fail if committed files drift from the configured seed.
  #
  # The artwork is maskable: the background is full bleed and every visible
  # element stays inside the centered circle of 40% radius that the maskable
  # icon contract guarantees is never cropped.
  #
  # PNG bytes are produced in pure Ruby (stdlib zlib) so generation works in
  # every environment without libvips or ImageMagick.
  module AppIcon
    PATH = "public/icon.svg"
    PNG_PATHS = {
      192 => "public/icon-192.png",
      512 => "public/icon-512.png",
      180 => "public/apple-touch-icon.png"
    }.freeze
    SIZE = 512
    CENTER = SIZE / 2
    # 40% of the canvas is the guaranteed-visible maskable safe zone; the mark
    # stays comfortably inside it.
    SAFE_RADIUS = (SIZE * 0.4).to_i
    OUTER_RADIUS = 144
    INNER_RADIUS = 64
    HEX = /\A#?(\h{6})\z/
    PNG_SIGNATURE = "\x89PNG\r\n\x1a\n".b

    class InvalidColor < ArgumentError; end

    # Normalizes "#6750a4" / "6750A4" to "#6750A4" and rejects anything else.
    def self.normalize_color(value)
      match = HEX.match(value.to_s.strip)
      raise InvalidColor, "expected a #RRGGBB color, got #{value.inspect}" if match.nil?

      "##{match[1].upcase}"
    end

    # WCAG relative luminance, used to choose a foreground that keeps the mark
    # visible against any seed color.
    def self.relative_luminance(color)
      channels = normalize_color(color)[1..].scan(/../).map do |pair|
        component = pair.to_i(16) / 255.0
        component <= 0.03928 ? component / 12.92 : (((component + 0.055) / 1.055)**2.4)
      end

      (0.2126 * channels[0]) + (0.7152 * channels[1]) + (0.0722 * channels[2])
    end

    def self.foreground_for(color)
      luminance = relative_luminance(color)
      on_white = 1.05 / (luminance + 0.05)
      on_black = (luminance + 0.05) / 0.05

      on_white >= on_black ? "#FFFFFF" : "#000000"
    end

    def self.svg(seed_color = Rails.configuration.x.foundation[:brand_seed_color])
      background = normalize_color(seed_color)
      foreground = foreground_for(background)

      <<~SVG
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 #{SIZE} #{SIZE}" width="#{SIZE}" height="#{SIZE}" role="img" aria-labelledby="title">
          <title id="title">Application icon</title>
          <!-- Generated by bin/rails foundation:icon from brand_seed_color #{background} in config/foundation.yml. Replace this file with your own square maskable mark. -->
          <rect width="#{SIZE}" height="#{SIZE}" fill="#{background}"/>
          <circle cx="#{CENTER}" cy="#{CENTER}" r="#{OUTER_RADIUS}" fill="#{foreground}"/>
          <circle cx="#{CENTER}" cy="#{CENTER}" r="#{INNER_RADIUS}" fill="#{background}"/>
        </svg>
      SVG
    end

    # Rasterizes the same mark as `svg` at `size`×`size` (RGB PNG).
    def self.png(size, seed_color = Rails.configuration.x.foundation[:brand_seed_color])
      dimension = Integer(size)
      raise ArgumentError, "size must be positive" unless dimension.positive?

      background = normalize_color(seed_color)
      foreground = foreground_for(background)
      bg = hex_to_rgb(background)
      fg = hex_to_rgb(foreground)

      scale = dimension.to_f / SIZE
      outer_r2 = (OUTER_RADIUS * scale)**2
      inner_r2 = (INNER_RADIUS * scale)**2
      cx = dimension / 2.0
      cy = dimension / 2.0

      raw = String.new(encoding: Encoding::BINARY)
      dimension.times do |y|
        raw << 0 # PNG filter: None
        py = (y + 0.5) - cy
        dimension.times do |x|
          px = (x + 0.5) - cx
          d2 = (px * px) + (py * py)
          rgb = if d2 <= inner_r2
            bg
          elsif d2 <= outer_r2
            fg
          else
            bg
          end
          raw << rgb.pack("C3")
        end
      end

      encode_png(dimension, dimension, raw)
    end

    def self.png_dimensions(bytes)
      data = bytes.to_s.b
      raise ArgumentError, "not a PNG" unless data.start_with?(PNG_SIGNATURE)

      data[16, 8].unpack("NN")
    end

    def self.write_all!(seed_color = Rails.configuration.x.foundation[:brand_seed_color], root: Rails.root)
      written = []
      svg_path = root.join(PATH)
      svg_path.write(svg(seed_color))
      written << PATH

      PNG_PATHS.each do |dimension, relative|
        path = root.join(relative)
        path.binwrite(png(dimension, seed_color))
        written << relative
      end

      written
    end

    def self.hex_to_rgb(color)
      normalize_color(color)[1..].scan(/../).map { |pair| pair.to_i(16) }
    end
    private_class_method :hex_to_rgb

    def self.encode_png(width, height, filtered_rgb)
      compressed = Zlib::Deflate.deflate(filtered_rgb)
      ihdr = [ width, height, 8, 2, 0, 0, 0 ].pack("N2C5")

      PNG_SIGNATURE + png_chunk("IHDR", ihdr) + png_chunk("IDAT", compressed) + png_chunk("IEND", "".b)
    end
    private_class_method :encode_png

    def self.png_chunk(type, data)
      type_bytes = type.b
      payload = data.b
      [ payload.bytesize ].pack("N") + type_bytes + payload + [ Zlib.crc32(type_bytes + payload) ].pack("N")
    end
    private_class_method :png_chunk
  end
end
