# frozen_string_literal: true

module Foundation
  # Deterministic application icon (SPEC M10.2).
  #
  # The mark is a placeholder derived from exactly one input — the
  # `brand_seed_color` in config/foundation.yml — so it can always be
  # regenerated from committed configuration instead of shipping an opaque
  # binary. `bin/rails foundation:icon` writes the SVG to public/icon.svg and
  # a test fails if the committed file drifts from the configured seed.
  #
  # The artwork is maskable: the background is full bleed and every visible
  # element stays inside the centered circle of 40% radius that the maskable
  # icon contract guarantees is never cropped.
  module AppIcon
    PATH = "public/icon.svg"
    SIZE = 512
    CENTER = SIZE / 2
    # 40% of the canvas is the guaranteed-visible maskable safe zone; the mark
    # stays comfortably inside it.
    SAFE_RADIUS = (SIZE * 0.4).to_i
    OUTER_RADIUS = 144
    INNER_RADIUS = 64
    HEX = /\A#?(\h{6})\z/

    class InvalidColor < ArgumentError; end

    # Normalizes "#6750a4" / "6750A4" to "#6750A4" and rejects anything else.
    def self.normalize_color(value)
      match = HEX.match(value.to_s.strip)
      raise InvalidColor, "expected a #RRGGBB color, got #{value.inspect}" if match.nil?

      "##{match[1].upcase}"
    end

    # WCAG relative luminance, used to choose a foreground that keeps the mark
    # visible against any seed color.
    def self.relative_luminance(color)
      channels = normalize_color(color)[1..].scan(/../).map do |pair|
        component = pair.to_i(16) / 255.0
        component <= 0.03928 ? component / 12.92 : (((component + 0.055) / 1.055)**2.4)
      end

      (0.2126 * channels[0]) + (0.7152 * channels[1]) + (0.0722 * channels[2])
    end

    def self.foreground_for(color)
      luminance = relative_luminance(color)
      on_white = 1.05 / (luminance + 0.05)
      on_black = (luminance + 0.05) / 0.05

      on_white >= on_black ? "#FFFFFF" : "#000000"
    end

    def self.svg(seed_color = Rails.configuration.x.foundation[:brand_seed_color])
      background = normalize_color(seed_color)
      foreground = foreground_for(background)

      <<~SVG
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 #{SIZE} #{SIZE}" width="#{SIZE}" height="#{SIZE}" role="img" aria-labelledby="title">
          <title id="title">Application icon</title>
          <!-- Generated by bin/rails foundation:icon from brand_seed_color #{background} in config/foundation.yml. Replace this file with your own square maskable mark. -->
          <rect width="#{SIZE}" height="#{SIZE}" fill="#{background}"/>
          <circle cx="#{CENTER}" cy="#{CENTER}" r="#{OUTER_RADIUS}" fill="#{foreground}"/>
          <circle cx="#{CENTER}" cy="#{CENTER}" r="#{INNER_RADIUS}" fill="#{background}"/>
        </svg>
      SVG
    end
  end
end
