import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { createHash } from "node:crypto"
import {
  Hct,
  SchemeTonalSpot,
  argbFromHex,
  hexFromArgb,
} from "@material/material-color-utilities"

const projectRoot = resolve(import.meta.dirname, "../../..")
const foundationYaml = await readFile(resolve(projectRoot, "config/foundation.yml"), "utf8")
const seedMatch = foundationYaml.match(/^\s*brand_seed_color:\s*["']?(#[0-9a-fA-F]{6})["']?\s*$/m)

if (!seedMatch) throw new Error("config/foundation.yml must define brand_seed_color as #RRGGBB")

const seed = seedMatch[1].toUpperCase()
const source = Hct.fromInt(argbFromHex(seed))
const roleNames = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "background", "onBackground", "surface", "onSurface", "surfaceVariant",
  "onSurfaceVariant", "outline", "outlineVariant", "shadow", "scrim",
  "inverseSurface", "inverseOnSurface", "inversePrimary", "surfaceDim",
  "surfaceBright", "surfaceContainerLowest", "surfaceContainerLow",
  "surfaceContainer", "surfaceContainerHigh", "surfaceContainerHighest",
  "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
  "secondaryFixed", "secondaryFixedDim", "onSecondaryFixed", "onSecondaryFixedVariant",
  "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
]

const kebab = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
const schemes = Object.fromEntries([false, true].map((dark) => {
  const scheme = new SchemeTonalSpot(source, dark, 0)
  const colors = Object.fromEntries(roleNames.map((name) => [kebab(name), hexFromArgb(scheme[name]).toUpperCase()]))
  return [dark ? "dark" : "light", colors]
}))

const metadata = {
  generator: "@material/material-color-utilities",
  version: "0.4.0",
  algorithm: "SchemeTonalSpot",
  variant: "Material dynamic color 2021",
  contrastLevel: 0,
  seed,
}
const payload = `${JSON.stringify({ metadata, schemes }, null, 2)}\n`
const payloadSha256 = createHash("sha256").update(payload).digest("hex")
const cssBlocks = Object.entries(schemes).map(([name, roles]) => {
  const selector = name === "light" ? ":root, [data-theme=\"light\"]" : "[data-theme=\"dark\"]"
  const declarations = Object.entries(roles).map(([role, color]) => `  --md-sys-color-${role}: ${color};`).join("\n")
  return `${selector} {\n${declarations}\n}`
})
const systemDark = Object.entries(schemes.dark).map(([role, color]) => `    --md-sys-color-${role}: ${color};`).join("\n")
const css = `/* Generated by tools/material/generate_tokens.mjs. Do not edit. */\n/* Seed ${seed}; @material/material-color-utilities 0.4.0; SchemeTonalSpot; contrast 0. */\n${cssBlocks.join("\n\n")}\n\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]):not([data-theme=\"dark\"]) {\n${systemDark}\n  }\n}\n`

const outputs = new Map([
  [resolve(projectRoot, "app/assets/stylesheets/material_tokens.css"), css],
  [resolve(projectRoot, "config/material_tokens.json"), payload],
  [resolve(projectRoot, "config/material_tokens.sha256"), `${payloadSha256}\n`],
])

if (process.argv.includes("--check")) {
  const mismatches = []
  for (const [path, expected] of outputs) {
    const actual = await readFile(path, "utf8").catch(() => "")
    if (actual !== expected) mismatches.push(path)
  }
  if (mismatches.length) {
    throw new Error(`Material tokens need regeneration:\n${mismatches.join("\n")}`)
  }
} else {
  await Promise.all([...outputs].map(([path, contents]) => writeFile(path, contents)))
}
